Global:
  algorithm: Rosetta
  use_gpu: true
  epoch_num: 400
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_Rosetta5/
  save_epoch_step: 10
  eval_batch_step: 500
  train_batch_size_per_card: 10
  test_batch_size_per_card: 5
  image_shape: [3, 32, 192]
  max_text_length: 10
  min_text_length: 4
  character_type: ch
  character_dict_path: ./ppocr/utils/dict/number_dict.txt
  loss_type: ctc
  distort: true
  debug: false
  reader_yml: ./configs/rec/rec_benchmark_reader.yml
  pretrain_weights: ./output/rec_Rosetta4/best_accuracy
  checkpoints:
  save_inference_dir:
  infer_img:

Architecture:
  function: ppocr.modeling.architectures.rec_model,RecModel

Backbone:
  function: ppocr.modeling.backbones.rec_mobilenet_v3,MobileNetV3
  scale: 0.5
  model_name: large

Head:
  function: ppocr.modeling.heads.rec_ctc_head,CTCPredict
  encoder_type: reshape
  
Loss:
  function: ppocr.modeling.losses.rec_ctc_loss,CTCLoss

Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.0005
  beta1: 0.9
  beta2: 0.999
  decay:
    function: cosine_decay
    step_each_epoch: 320
    total_epoch: 400
