TrainReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
  num_workers: 8
  img_set_dir: ./train_data/rec_train_data4
  label_file_path: ./train_data/rec_gt_train4.txt
  
EvalReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
  img_set_dir: ./train_data/rec_train_data4
  label_file_path: ./train_data/rec_gt_test4.txt

TestReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
  img_set_dir: ./train_data/rec_train_data4
  label_file_path: ./train_data/rec_gt_test4.txt
