TrainReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
  num_workers: 8
  img_set_dir: ./train_data/rec_train_data2
  label_file_path: ./train_data/rec_gt_train2.txt
  
EvalReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
  img_set_dir: ./train_data/rec_train_data2
  label_file_path: ./train_data/rec_gt_test2.txt

TestReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
  img_set_dir: ./train_data/rec_train_data2
  label_file_path: ./train_data/rec_gt_test2.txt
