TrainReader:
  reader_function: ppocr.data.det.dataset_traversal,TrainReader
  process_function: ppocr.data.det.sast_process,SASTProcessTrain
  num_workers: 8
  img_set_dir: ./train_data/train_data/
  label_file_path: ./train_data/label.txt
  data_ratio_list: 0.1
  min_crop_side_ratio: 0.3
  min_crop_size: 24
  min_text_size: 4
  max_text_size: 20

EvalReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.sast_process,SASTProcessTest
  img_set_dir: ./train_data/icdar2015/text_localization/
  label_file_path: ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
  max_side_len: 1536
  
TestReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.sast_process,SASTProcessTest
  max_side_len: 1536
