TrainReader:
  reader_function: ppocr.data.det.dataset_traversal,TrainReader
  process_function: ppocr.data.det.east_process,EASTProcessTrain
  num_workers: 8
  img_set_dir: ./train_data/train_data/
  label_file_path: ./train_data/train_label.txt
  background_ratio: 0.125
  min_crop_side_ratio: 0.1
  min_text_size: 1

EvalReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.east_process,EASTProcessTest
  img_set_dir: ./train_data/train_data/
  label_file_path: ./train_data/test_label.txt
  
TestReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.east_process,EASTProcessTest
  img_set_dir: ./train_data/train_data/
  label_file_path: ./train_data/test_label.txt
  do_eval: True
