TrainReader:
  reader_function: ppocr.data.det.dataset_traversal,TrainReader
  process_function: ppocr.data.det.db_process,DBProcessTrain
  num_workers: 8
  img_set_dir: ./train_data/train_data/
  label_file_path: ./train_data/train_Label3.txt

EvalReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  img_set_dir: ./train_data/train_data/
  label_file_path: ./train_data/test_Label3.txt
  test_image_shape: [960, 960]
  
TestReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  img_set_dir: ./train_data/train_data/
  label_file_path: ./train_data/test_Label3.txt
  do_eval: True
