# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['PPOCRLabel.py','paddleocr.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\tools\\infer\\predict_cls.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\tools\\infer\\predict_det.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\tools\\infer\\predict_rec.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\tools\\infer\\predict_system.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\tools\\infer\\utility.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\utils\\character.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\utils\\check.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\utils\\save_load.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\utils\\stats.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\utils\\utility.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\reader_main.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\cls\\dataset_traversal.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\cls\\randaugment.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\det\\data_augment.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\det\\dataset_traversal.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\det\\db_process.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\det\\east_process.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\det\\make_border_map.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\det\\make_shrink_map.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\det\\random_crop_data.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\det\\sast_process.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\rec\\dataset_traversal.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\rec\\img_tools.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\rec\\text_image_aug\\augment.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\data\\rec\\text_image_aug\\warp_mls.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\postprocess\\db_postprocess.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\postprocess\\east_postprocess.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\postprocess\\locality_aware_nms.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\postprocess\\sast_postprocess.py',
			  'G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\optimizer.py',
			 ],
             pathex=['G:\Anaconda\envs\paddle2.0\Lib',
			 'G:\\Anaconda\\envs\\paddle2.0\\Lib\\site-packages\\',
			 'G:\\Anaconda\\envs\\paddle2.0\\Lib\\site-packages\\PyQt5',
			 'G:\\Anaconda\\envs\\paddle2.0\\Lib\\site-packages\\paddle',
			 'G:\\Anaconda\\envs\\paddle2.0\\Lib\\site-packages\\paddle\\libs'],
             binaries=[('G:\\Anaconda\\envs\\paddle2.0\\Lib\\site-packages\\paddle\\libs','.')],
             datas=[('G:\\lyb\\PaddleOCR\\PPOCRLabel\\resources\\icons','resource\\icons'),
			 ('G:\\lyb\\PaddleOCR\\PPOCRLabel\\resources\\strings','resource\\strings'),
			 ('G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr\\utils\\dict\\number_dict.txt','dict'),
			 ('G:\\lyb\\PaddleOCR\\PPOCRLabel\\ppocr','ocr')],
             hiddenimports=['ppocr','skimage.filters.rank.core_cy_3d','pyclipper','imgaug','paddle','cv2','tqdm','imghdr'],
             hookspath=[],
             runtime_hooks=[],
             excludes=['matplotlib'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='OCRTool',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
